export default {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.617689, 11.680564],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-1",
        phoneFormatted: "(202) 234-7336",
        phone: 2022347336,
        name: "Chundayil Ganapathi Temple",
        address: "Edacheri Chundayil Road, Edacheri, Purameri, Kerala 673502",
        category: "grade1",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 15th St NW",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.617733, 11.675017],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-2",
        phoneFormatted: "(202) 507-8357",
        phone: 2025078357,
        name: "Shiva Subramanya Temple Allasseri",
        address: "Purameri, Kerala 673502",
        category: "grade2",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 22nd St NW",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "murugan",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.615987, 11.67273],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-3",
        phoneFormatted: "(202) 387-9338",
        phone: 2023879338,
        name: "Alissery chelottiIllathu karimKuttichathan Temple",
        address: "Purameri, Kerala 673502",
        category: "grade2",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at Dupont Circle",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "kuttichattan",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.616836, 11.669071],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-4",
        phoneFormatted: "(202) 337-9338",
        phone: 2023379338,
        name: "Koyambatta Bagavathy Temple",
        address: "Edacheri, Purameri, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 34th St NW",
        postalCode: 673503,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.612592, 11.663339],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-5",
        phoneFormatted: "(202) 547-9338",
        phone: 2025479338,
        name: "Sree kakkannoor Temple",
        address: "KAKKANNOOR, Edacheri, Vatakara, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "btwn 2nd & 3rd Sts. SE",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.611999, 11.659046],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-6",
        phone: 2025479338,
        name: "Kaliyamvelli temple Entrance",
        address: "Edacheri, Purameri, Kerala 673501",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.618941, 11.65432],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-7",
        phoneFormatted: "(301) 654-7336",
        phone: 3016547336,
        name: "Vengoli Ganapathi Ayappa Temple",
        address: "Edacheri, Purameri, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: ["ayyappan"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.624461, 11.665975],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-8",
        phoneFormatted: "(571) 203-0082",
        phone: 5712030082,
        name: "Narasimha Murthy Temple",
        address: "Vengoli - Muthuvada Rd, Edacheri, Purameri, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "btw Explorer & Library",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "narasimha",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.645313, 11.654694],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-9",
        phoneFormatted: "(703) 522-2016",
        phone: 7035222016,
        name: "Vayal pothi Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at N Randolph St.",
        postalCode: 673503,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.65547, 11.660754],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-10",
        phoneFormatted: "(610) 642-9400",
        phone: 6106429400,
        name: "Thanari Bhagavathi Temple",
        address:
          "Kunhalloor-Thanneerpanthal Rd, Vilathapuram, Katameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.642707, 11.675928],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-11",
        phoneFormatted: "(215) 386-1365",
        phone: 2153861365,
        name: "Kakkamvelly Sreekrishna Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "krishna",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.631285, 11.675173],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-12",
        phoneFormatted: "(202) 331-3355",
        phone: 2023313355,
        name: "Kozhukkanoor Ayyappa Bhajana Matam",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.628784, 11.668402],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-13",
        phoneFormatted: "(202) 234-7337",
        phone: 4771159162,
        name: "Elampilayi Bhagavathi Temple",
        address: "Purameri, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.621219, 11.683519],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-14",
        phoneFormatted: "(202) 507-8358",
        phone: 5000950480,
        name: "Othayoth Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.618151, 11.685691],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-15",
        phoneFormatted: "(202) 387-9339",
        phone: 5230741797,
        name: "Ayyappan Kavu Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ayyappan",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.608826, 11.685977],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-16",
        phoneFormatted: "(202) 337-9339",
        phone: 5460533114,
        name: "Poyanneri Hindu Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673503,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.60949, 11.689199],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-17",
        phoneFormatted: "(202) 547-9339",
        phone: 5690324431,
        name: "Paremmal Bhagavathi Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.611262, 11.687603],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-18",
        phone: 5920115749,
        name: "Vallil Sree Ayyappan Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ayyappan",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.612265, 11.664825],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-19",
        phoneFormatted: "(301) 654-7337",
        phone: 6149907066,
        name: "sree koroth balasubrahmanya temple.",
        address: "Kakkannur, Edacheri, PO, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.635355, 11.668879],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-20",
        phoneFormatted: "(571) 203-0083",
        phone: 6379698383,
        name: "Udayapuram Maha Siva Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: ["ayyappan", "bhagavathi", "saraswathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.640479, 11.662109],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-21",
        phoneFormatted: "(703) 522-2017",
        phone: 6609489700,
        name: "Kunhalloor Narasimha Moorthy Temple",
        address: "Purameri - Kuningad Rd, Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "narasimha",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.639444, 11.659632],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-22",
        phoneFormatted: "(610) 642-9401",
        phone: 6839281017,
        name: "Annapoornesvary Temple",
        address: "Purameri - Kuningad Rd, Purameri, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.636268, 11.669932],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "T0003",
        home_pic: "KL13-23",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Karayat Maha Vishnu Temples",
        address: "Purameri - Kuningad Rd, Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["ayyappan", "bhagavathi"],
        },
        festivals: {
          name: "Aarattu",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.632815, 11.664372],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-24",
        phoneFormatted: "(202) 331-3356",
        phone: 7298863652,
        name: "AraamValli Bhagavathi Temple",
        address: "KVLP School Rd, Purameri, Kerala 673502",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.632885, 11.672674],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-25",
        phoneFormatted: "(202) 234-7338",
        phone: 7528654969,
        name: "Vettakkorumakan Temple",
        address: "Purameri, Kerala 673503",
        category: "grade4",
        city: "Purameri",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673502,
        state: "Kerala",
        diety: {
          main: "kuttichattan",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.6196829576727, 11.598302924721535],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "T0001",
        home_pic: "KL13-26",
        phoneFormatted: "(202) 234-7338",
        phone: 7528654969,
        name: "Lokanarkavu Temple",
        address: "Kavil Rd, Villiappally, Vatakara, Kerala",
        city: "Vatakara",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673504,
        state: "Kerala",
        diety: {
          main: "durga",
          sub: [],
        },
        festivals: {
          name: "Pooram",
          from: "2021-03-28",
          to: "2021-04-02",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.629914, 11.598009],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-27",
        phoneFormatted: "(202) 234-7338",
        phone: 7528654969,
        name: "Memunda Madam Naga Temple",
        address: "Memunda, Vatakara, Kerala 673104",
        city: "Vatakara",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673504,
        state: "Kerala",
        diety: {
          main: "nagaraja",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.786874, 11.248776],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-28",
        phoneFormatted: "(202) 234-7338",
        phone: 7528654969,
        name: "Thali Ganapathi Temple",
        address: "Ganapathi Temple Rd, Palayam, Kozhikode, Kerala",
        city: "Vatakara",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673002,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.342123, 9.945321],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-29",
        phoneFormatted: "(202) 234-7338",
        phone: 7528654969,
        name: "Sree Poornathrayeesa, Tripunithura",
        address: "ottakakom, Thrippunithura, Eranakulam, Kerala 682301",
        city: "Thrippunithura",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Eranakulam",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673002,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Vrishchikotsavam",
          from: "2020-11-15",
          to: "2020-12-14",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.21449, 10.524994],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-30",
        phoneFormatted: "(202) 234-7339",
        phone: 7528654969,
        name: "Sri Vadakkunnathan Temple",
        address: "Thrissur",
        city: "Thrissur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "thrissur",
        district: "Thrissur",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673003,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: [],
        },
        festivals: {
          name: "Thrissur Pooram",
          from: "2021-04-22",
          to: "2021-04-23",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [77.082052, 9.433863],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-31",
        phoneFormatted: "(202) 234-7340",
        phone: 7528654969,
        name: "Sabarimala",
        address: "Pathanamthitta",
        city: "Pathanamthitta",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Pathanamthitta",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673004,
        state: "Kerala",
        diety: {
          main: "ayyappan",
          sub: [],
        },
        festivals: {
          name: "Makaravilakku",
          from: "2021-01-13",
          to: "2021-01-13",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.955464, 8.470138],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-32",
        phoneFormatted: "(202) 234-7341",
        phone: 7528654969,
        name: "Attukal Bhagavathy Temple",
        address: "Thiruvananthapuram",
        city: "Thiruvananthapuram",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Thiruvananthapuram",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673005,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "Attukal Pongala",
          from: "2021-02-26",
          to: "2021-02-26",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.988883, 8.445863],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-33",
        phoneFormatted: "(202) 234-7342",
        phone: 7528654969,
        name: "Vellayani Devi Temple",
        address: "Nemom, Vellayani, Thiruvananthapuram, Kerala 695020",
        city: " Vellayani",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Thiruvananthapuram",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673006,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Kaaliyootu",
          from: "2020-04-21",
          to: "2020-04-21",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.943569, 8.483001],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-34",
        phoneFormatted: "(202) 234-7343",
        phone: 7528654969,
        name: "Padmanabhaswamy Temple",
        address: "Thiruvananthapuram, Kerala",
        city: "Thiruvananthapuram",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Thiruvananthapuram",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673007,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: [],
        },
        festivals: {
          name: "Painkuni Utsavam",
          from: "2021-03-19",
          to: "2021-03-28",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.395936, 9.750221],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-35",
        phoneFormatted: "(202) 234-7344",
        phone: 7528654969,
        name: "Vaikom Mahadeva Temple",
        address: "Vaikom, Kottayam, Kerala",
        city: "Vaikom",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kottayam",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673008,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: [],
        },
        festivals: {
          name: "Vaikathashtami",
          from: "2020-12-07",
          to: "2020-12-07",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.198388, 10.227077],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-36",
        phoneFormatted: "(202) 234-7345",
        phone: 7528654969,
        name: "Sree Kurumba Bhagavathy Temple",
        address: "Kodungallour, Thrissur",
        city: "Kodungallour",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Thrissur",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673009,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "Kodungalloor Bharani",
          from: "2021-03-16",
          to: "2021-03-17Koo",
        },
      },
    },

    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.039337, 10.594815],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-37",
        phoneFormatted: "(202) 234-7346",
        phone: 7528654969,
        name: "guruvayoor sree krishna temple",
        address: "Guruvayoor Thrissur",
        city: "Guruvayoor",
        ward: "0",
        village: "Guruvayur",
        panchayath: "Guruvayur",
        taluk: "Chavakkad",
        district: "Thrissur",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673010,
        state: "Kerala",
        diety: {
          main: "krishna",
          sub: [],
        },
        festivals: {
          name: "Ekadashi",
          from: "2020-11-25",
          to: "2020-11-25",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.515805, 9.22962],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-38",
        phoneFormatted: "(202) 234-7347",
        phone: 7528654969,
        name: "Chettikulangara Devi Temple",
        address: "Mavelikara,Alappuzha",
        city: "Chettikulangara",
        ward: "0",
        village: "Chettikulangara",
        panchayath: "Chettikulangara",
        taluk: "Mavelikkara",
        district: "Alappuzha",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673011,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Chettikulangara Kumbha Bharani",
          from: "2021-02-17",
          to: "2021-02-17",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.354553, 10.116896],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-39",
        phoneFormatted: "(202) 234-7348",
        phone: 7528654969,
        name: "Aluva Mahadeva Temple",
        address: "Maradu, Eranakulam",
        city: "Maradu",
        ward: "0",
        village: "Aluva",
        panchayath: "Aluva",
        taluk: "Aluva",
        district: "Ernakulam",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673012,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: [],
        },
        festivals: {
          name: "Maha Shivaratri",
          from: "2021-03-10",
          to: "2021-03-10",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.636609, 9.193161],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-40",
        phoneFormatted: "(202) 234-7349",
        phone: 7528654969,
        name: "Padanilam Parabrahma Temple",
        address: "Mavelikkara, Pathanamthitta",
        city: "Mavelikkara",
        ward: "0",
        village: "Padanilam",
        panchayath: "Nooranad",
        taluk: "Mavelikkara",
        district: "Alappuzha",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673013,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Maha Shivaratri",
          from: "2021-03-10",
          to: "2021-03-10",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.676875, 9.457561],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-41",
        phoneFormatted: "(202) 234-7350",
        phone: 7528654969,
        name: "Anikkattilamma Siva Parvathy Temple",
        address: "Mallappally,Tiruvalla, kottayam",
        city: "Mallappally",
        ward: "0",
        village: "Anicadu",
        panchayath: "Anicadu",
        taluk: "Mallappally",
        district: "Pathanamthitta",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673014,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: [],
        },
        festivals: {
          name: "Ponkalamaholsavam",
          from: "2021-02-12",
          to: "2021-02-19",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.603107, 10.592681],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-42",
        phoneFormatted: "(202) 234-7351",
        phone: 7528654969,
        name: "Nellikulangara Bhagavathy Temple",
        address: "Nenmara, Vallanghy, palakkad",
        city: "Nenmara",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Palakkad",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673015,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "Vela",
          from: "2021-04-02",
          to: "2021-04-02",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.647838, 10.795128],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-43",
        phoneFormatted: "(202) 234-7352",
        phone: 7528654969,
        name: "Sree Viswanatha Swamy Temple",
        address: "Kalpathi, Palakkad",
        city: "Kalpathi",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Palakkad",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673016,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: [],
        },
        festivals: {
          name: "Kalpathi Ratholsavam",
          from: "2021-11-13",
          to: "2021-11-15",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.731486, 9.155547],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-44",
        phoneFormatted: "(202) 234-7353",
        phone: 7528654969,
        name: "Sree Parthasarathy Temple",
        address: "Adoor, Pathanamthitta",
        city: "Adoor",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Pathanamthitta",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673017,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Adoor Gajamela",
          from: "2021-02-03",
          to: "2021-02-03",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.501389, 9.284722],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-45",
        phoneFormatted: "(202) 234-7354",
        phone: 7528654969,
        name: "Sree Subrahmanya Swamy Temple",
        address: "Harippad, Alappuzha",
        city: "Harippad",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Alappuzha",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673018,
        state: "Kerala",
        diety: {
          main: "murugan",
          sub: [],
        },
        festivals: {
          name: "Thaipooyam\u00A0Mahotsavam",
          from: "2021-01-27",
          to: "2021-01-27",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.212548, 10.502898],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-46",
        phoneFormatted: "(202) 234-7355",
        phone: 7528654969,
        name: "Koorkancherry Sree Maheswara Temple",
        address: "Koorkancherry, Thrissur",
        city: "Koorkancherry",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Thrissur",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673019,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: [],
        },
        festivals: {
          name: "Thaipooyam Mahotsavam",
          from: "2021-01-27",
          to: "2021-01-27",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.257393, 10.523234],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-47",
        phoneFormatted: "(202) 234-7356",
        phone: 7528654969,
        name: "Machattu Thiruvanikavu Temple",
        address: "Vadakkancherry, Thrissur",
        city: "Vadakkancherry",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Thrissur",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673020,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Machattu Mamangam",
          from: "2021-02-22",
          to: "2021-02-22",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.561074, 9.673981],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-48",
        phoneFormatted: "(202) 234-7357",
        phone: 7528654969,
        name: "Ettumanoor Mahadeva Temple",
        address: "Ettumanoor, Kottayam",
        city: "Ettumanoor",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kottayam",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673021,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: [],
        },
        festivals: {
          name: "Ezhara Ponnana",
          from: "2021-02-20",
          to: "2021-02-20",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.445664, 9.290048],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-49",
        phoneFormatted: "(202) 234-7358",
        phone: 7528654969,
        name: "Sree Nagaraja Temple, Mannarasala",
        address: "Harippad, Alappuzha",
        city: "Harippad",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Alappuzha",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673022,
        state: "Kerala",
        diety: {
          main: "nagaraja",
          sub: [],
        },
        festivals: {
          name: "Mannarasala Ayilyam",
          from: "2021-10-29",
          to: "2021-10-29",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.583682, 9.170339],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-50",
        phoneFormatted: "(202) 234-7359",
        phone: 7528654969,
        name: "Sree Nagaraja Swami Temple",
        address: "Vettikode, Alappuzha",
        city: "Vettikode",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Alappuzha",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673023,
        state: "Kerala",
        diety: {
          main: "nagaraja",
          sub: [],
        },
        festivals: {
          name: "Ayilyam Vettikode",
          from: "2021-10-01",
          to: "2021-10-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.510565, 9.13602],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-51",
        phoneFormatted: "(202) 234-7360",
        phone: 7528654969,
        name: "Ochira Parabrahma Temple",
        address: "Ochira, Kollam",
        city: "Ochira",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kollam",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673024,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Ochira Kali",
          from: "2021-06-14",
          to: "2021-06-15",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.657727, 9.102684],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-52",
        phoneFormatted: "(202) 234-7361",
        phone: 7528654969,
        name: "Poruvazhi Malanada Temple",
        address: "Poruvazhi , Kollam",
        city: "Poruvazhi ",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kollam",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673025,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: [],
        },
        festivals: {
          name: "Malanada Kettukazcha",
          from: "2021-03-25",
          to: "2021-03-25",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [76.51878, 9.590665],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-53",
        phoneFormatted: "(202) 234-7362",
        phone: 7528654969,
        name: "Thirunakkara Mahadeva Temple",
        address: "Thirunakkara, Kottayam",
        city: "Thirunakkara",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kottayam",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673026,
        state: "Kerala",
        diety: {
          main: "shiva",
          sub: [],
        },
        festivals: {
          name: "Thirunakkara Arattu",
          from: "2021-03-23",
          to: "2021-03-23",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.678436, 11.458475],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-54",
        phoneFormatted: "(202) 234-7363",
        phone: 7528654969,
        name: "Pisharikavu Temple",
        address: "Koyilandy, Kozhikode",
        city: "Koyilandy",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Koyilandy",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673027,
        state: "Kerala",
        diety: {
          main: "bhagavati",
          sub: [],
        },
        festivals: {
          name: "Pisharikav Kaaliyattom",
          from: "2021-04-05",
          to: "2021-04-12",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.81505751, 11.3808081211035],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-55",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Perumeenpuram Maha Vishnu Temple",
        address: "Perumeen puram, Kakkur, Kerala 673619",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673619,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8272769698345, 11.404617522621],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-56",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Aamamangalam Maha Vishnu Temple",
        address: "Kakkur, Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8658903, 11.4235964242408],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-57",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Pannyamvalli Varyam Madam Vishnu Temple",
        address: "12, Nanminda, Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8128340537497, 11.3941749964272],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-58",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Thrukkoyikkal Narasimha Temple",
        address: "Kakkur,Kozhikode,Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.802173, 11.401456],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-59",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Theerthamkara Vamana Temple",
        address: "Kakkur,Kozhikode,Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8152032404244, 11.3741638787505],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-60",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Kakkur Parasurama Temple (ruiend)",
        address: "Kozhikode, Kakkur, Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8241925820778, 11.3892982959923],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-61",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Ramallur Sreerama Temple",
        address: "Kozhikode, Kakkur, Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8252163314944, 11.3814857675111],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-62",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Kavil Balarama Temple",
        address: "Kozhikode,Narikkuni Rd,Kakkur, Kerala 673585",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673585,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8000232857354, 11.3836845849537],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-63",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Inthad Sree Maha Vishnu Temple ",
        address: "Pavandoor, Kakkur, Kozhikode, Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.8180201227717, 11.3837890221216],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "",
        home_pic: "KL13-64",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Perumeenpuram Vishnu Temple(kalkki) ",
        address: "Kakkur, Kerala 673613",
        city: "Kakkur",
        ward: "0",
        village: "Purameri",
        panchayath: "Purameri",
        taluk: "Thamarassery",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "vishnu",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [75.62792996490312, 11.553261040827115],
      },
      Calc_distance: 0,
      pooja_schedule: ["5:30am-9:00am", "5:30pm-8:30pm"],
      properties: {
        TID: "T0002",
        home_pic: "KL13-65",
        phoneFormatted: "(215) 386-1366",
        phone: 7069072335,
        name: "Palayad Theru Bhagavathi Temple",
        address: "Palayad theru, Palayad Nada, Kozhikode, Kerala 673631",
        city: "Palayad",
        ward: "0",
        village: "Palayad",
        panchayath: "Maniyoor",
        taluk: "Vatakara",
        district: "Kozhikode",
        country: "India",
        crossStreet: "at 19th St",
        postalCode: 673613,
        state: "Kerala",
        diety: {
          main: "ganapathi",
          sub: ["bhagavathi"],
        },
        festivals: {
          name: "None",
          from: "2021-01-01",
          to: "2021-01-01",
        },
      },
    },
  ],
};
